use crate::identifier_quad::*;

pub enum TreeForFour<I>
where I: Identifier
{
    SPOG(OnceTreeSet<I, Subject, Predicate, Object, Graph>),
    SPGO(OnceTreeSet<I, Subject, Predicate, Graph, Object>),
    SOPG(OnceTreeSet<I, Subject, Object, Predicate, Graph>),
    SOGP(OnceTreeSet<I, Subject, Object, Graph, Predicate>),
    SGPO(OnceTreeSet<I, Subject, Graph, Predicate, Object>),
    SGOP(OnceTreeSet<I, Subject, Graph, Object, Predicate>),
    PSOG(OnceTreeSet<I, Predicate, Subject, Object, Graph>),
    PSGO(OnceTreeSet<I, Predicate, Subject, Graph, Object>),
    POSG(OnceTreeSet<I, Predicate, Object, Subject, Graph>),
    POGS(OnceTreeSet<I, Predicate, Object, Graph, Subject>),
    PGSO(OnceTreeSet<I, Predicate, Graph, Subject, Object>),
    PGOS(OnceTreeSet<I, Predicate, Graph, Object, Subject>),
    OSPG(OnceTreeSet<I, Object, Subject, Predicate, Graph>),
    OSGP(OnceTreeSet<I, Object, Subject, Graph, Predicate>),
    OPSG(OnceTreeSet<I, Object, Predicate, Subject, Graph>),
    OPGS(OnceTreeSet<I, Object, Predicate, Graph, Subject>),
    OGSP(OnceTreeSet<I, Object, Graph, Subject, Predicate>),
    OGPS(OnceTreeSet<I, Object, Graph, Predicate, Subject>),
    GSPO(OnceTreeSet<I, Graph, Subject, Predicate, Object>),
    GSOP(OnceTreeSet<I, Graph, Subject, Object, Predicate>),
    GPSO(OnceTreeSet<I, Graph, Predicate, Subject, Object>),
    GPOS(OnceTreeSet<I, Graph, Predicate, Object, Subject>),
    GOSP(OnceTreeSet<I, Graph, Object, Subject, Predicate>),
    GOPS(OnceTreeSet<I, Graph, Object, Predicate, Subject>),
}

impl<I> TreeForFour<I>
where I: Identifier {
    pub fn new(order: &[usize; 4]) -> Option<TreeForFour<I>> {
        match order {
            [0, 1, 2, 3] => Some(Self::SPOG( OnceTreeSet::new())),
            [0, 1, 3, 2] => Some(Self::SPGO( OnceTreeSet::new())),
            [0, 2, 1, 3] => Some(Self::SOPG( OnceTreeSet::new())),
            [0, 2, 3, 1] => Some(Self::SOGP( OnceTreeSet::new())),
            [0, 3, 1, 2] => Some(Self::SGPO( OnceTreeSet::new())),
            [0, 3, 2, 1] => Some(Self::SGOP( OnceTreeSet::new())),
            [1, 0, 2, 3] => Some(Self::PSOG( OnceTreeSet::new())),
            [1, 0, 3, 2] => Some(Self::PSGO( OnceTreeSet::new())),
            [1, 2, 0, 3] => Some(Self::POSG( OnceTreeSet::new())),
            [1, 2, 3, 0] => Some(Self::POGS( OnceTreeSet::new())),
            [1, 3, 0, 2] => Some(Self::PGSO( OnceTreeSet::new())),
            [1, 3, 2, 0] => Some(Self::PGOS( OnceTreeSet::new())),
            [2, 0, 1, 3] => Some(Self::OSPG( OnceTreeSet::new())),
            [2, 0, 3, 1] => Some(Self::OSGP( OnceTreeSet::new())),
            [2, 1, 0, 3] => Some(Self::OPSG( OnceTreeSet::new())),
            [2, 1, 3, 0] => Some(Self::OPGS( OnceTreeSet::new())),
            [2, 3, 0, 1] => Some(Self::OGSP( OnceTreeSet::new())),
            [2, 3, 1, 0] => Some(Self::OGPS( OnceTreeSet::new())),
            [3, 0, 1, 2] => Some(Self::GSPO( OnceTreeSet::new())),
            [3, 0, 2, 1] => Some(Self::GSOP( OnceTreeSet::new())),
            [3, 1, 0, 2] => Some(Self::GPSO( OnceTreeSet::new())),
            [3, 1, 2, 0] => Some(Self::GPOS( OnceTreeSet::new())),
            [3, 2, 0, 1] => Some(Self::GOSP( OnceTreeSet::new())),
            [3, 2, 1, 0] => Some(Self::GOPS( OnceTreeSet::new())),
            [_, _, _, _] => None,
        }
    }

    pub fn new_instanciated(order: &[usize; 4]) -> Option<TreeForFour<I>> {
        match order {
            [0, 1, 2, 3] => Some(Self::SPOG( OnceTreeSet::new_instanciated())),
            [0, 1, 3, 2] => Some(Self::SPGO( OnceTreeSet::new_instanciated())),
            [0, 2, 1, 3] => Some(Self::SOPG( OnceTreeSet::new_instanciated())),
            [0, 2, 3, 1] => Some(Self::SOGP( OnceTreeSet::new_instanciated())),
            [0, 3, 1, 2] => Some(Self::SGPO( OnceTreeSet::new_instanciated())),
            [0, 3, 2, 1] => Some(Self::SGOP( OnceTreeSet::new_instanciated())),
            [1, 0, 2, 3] => Some(Self::PSOG( OnceTreeSet::new_instanciated())),
            [1, 0, 3, 2] => Some(Self::PSGO( OnceTreeSet::new_instanciated())),
            [1, 2, 0, 3] => Some(Self::POSG( OnceTreeSet::new_instanciated())),
            [1, 2, 3, 0] => Some(Self::POGS( OnceTreeSet::new_instanciated())),
            [1, 3, 0, 2] => Some(Self::PGSO( OnceTreeSet::new_instanciated())),
            [1, 3, 2, 0] => Some(Self::PGOS( OnceTreeSet::new_instanciated())),
            [2, 0, 1, 3] => Some(Self::OSPG( OnceTreeSet::new_instanciated())),
            [2, 0, 3, 1] => Some(Self::OSGP( OnceTreeSet::new_instanciated())),
            [2, 1, 0, 3] => Some(Self::OPSG( OnceTreeSet::new_instanciated())),
            [2, 1, 3, 0] => Some(Self::OPGS( OnceTreeSet::new_instanciated())),
            [2, 3, 0, 1] => Some(Self::OGSP( OnceTreeSet::new_instanciated())),
            [2, 3, 1, 0] => Some(Self::OGPS( OnceTreeSet::new_instanciated())),
            [3, 0, 1, 2] => Some(Self::GSPO( OnceTreeSet::new_instanciated())),
            [3, 0, 2, 1] => Some(Self::GSOP( OnceTreeSet::new_instanciated())),
            [3, 1, 0, 2] => Some(Self::GPSO( OnceTreeSet::new_instanciated())),
            [3, 1, 2, 0] => Some(Self::GPOS( OnceTreeSet::new_instanciated())),
            [3, 2, 0, 1] => Some(Self::GOSP( OnceTreeSet::new_instanciated())),
            [3, 2, 1, 0] => Some(Self::GOPS( OnceTreeSet::new_instanciated())),
            [_, _, _, _] => None,
        }
    }

    pub fn exists(&self) -> bool {
        match &self {
            Self::SPOG(tree) => tree.exists(),
            Self::SPGO(tree) => tree.exists(),
            Self::SOPG(tree) => tree.exists(),
            Self::SOGP(tree) => tree.exists(),
            Self::SGPO(tree) => tree.exists(),
            Self::SGOP(tree) => tree.exists(),
            Self::PSOG(tree) => tree.exists(),
            Self::PSGO(tree) => tree.exists(),
            Self::POSG(tree) => tree.exists(),
            Self::POGS(tree) => tree.exists(),
            Self::PGSO(tree) => tree.exists(),
            Self::PGOS(tree) => tree.exists(),
            Self::OSPG(tree) => tree.exists(),
            Self::OSGP(tree) => tree.exists(),
            Self::OPSG(tree) => tree.exists(),
            Self::OPGS(tree) => tree.exists(),
            Self::OGSP(tree) => tree.exists(),
            Self::OGPS(tree) => tree.exists(),
            Self::GSPO(tree) => tree.exists(),
            Self::GSOP(tree) => tree.exists(),
            Self::GPSO(tree) => tree.exists(),
            Self::GPOS(tree) => tree.exists(),
            Self::GOSP(tree) => tree.exists(),
            Self::GOPS(tree) => tree.exists(),
        }
    }

    pub fn index_conformance(&self, can_build: bool, pattern_layout: &[Option<I>; 4]) -> Option<usize>{
        match &self {
            Self::SPOG(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::SPGO(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::SOPG(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::SOGP(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::SGPO(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::SGOP(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::PSOG(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::PSGO(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::POSG(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::POGS(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::PGSO(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::PGOS(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::OSPG(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::OSGP(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::OPSG(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::OPGS(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::OGSP(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::OGPS(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::GSPO(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::GSOP(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::GPSO(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::GPOS(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::GOSP(tree) => tree.index_conformance(can_build, &pattern_layout),
            Self::GOPS(tree) => tree.index_conformance(can_build, &pattern_layout),
        }
    }

    pub fn initialize<'a>(&self, iter: OnceTreeSetIterator<'a, I>) {
        match &self {
            Self::SPOG(tree) => tree.initialize(iter),
            Self::SPGO(tree) => tree.initialize(iter),
            Self::SOPG(tree) => tree.initialize(iter),
            Self::SOGP(tree) => tree.initialize(iter),
            Self::SGPO(tree) => tree.initialize(iter),
            Self::SGOP(tree) => tree.initialize(iter),
            Self::PSOG(tree) => tree.initialize(iter),
            Self::PSGO(tree) => tree.initialize(iter),
            Self::POSG(tree) => tree.initialize(iter),
            Self::POGS(tree) => tree.initialize(iter),
            Self::PGSO(tree) => tree.initialize(iter),
            Self::PGOS(tree) => tree.initialize(iter),
            Self::OSPG(tree) => tree.initialize(iter),
            Self::OSGP(tree) => tree.initialize(iter),
            Self::OPSG(tree) => tree.initialize(iter),
            Self::OPGS(tree) => tree.initialize(iter),
            Self::OGSP(tree) => tree.initialize(iter),
            Self::OGPS(tree) => tree.initialize(iter),
            Self::GSPO(tree) => tree.initialize(iter),
            Self::GSOP(tree) => tree.initialize(iter),
            Self::GPSO(tree) => tree.initialize(iter),
            Self::GPOS(tree) => tree.initialize(iter),
            Self::GOSP(tree) => tree.initialize(iter),
            Self::GOPS(tree) => tree.initialize(iter),
        }
    }

    pub fn get_quads<'a>(&'a self, pattern: [Option<I>; 4]) -> OnceTreeSetIterator<'a, I>{
        match &self {
            Self::SPOG(tree) => tree.get_quads(pattern),
            Self::SPGO(tree) => tree.get_quads(pattern),
            Self::SOPG(tree) => tree.get_quads(pattern),
            Self::SOGP(tree) => tree.get_quads(pattern),
            Self::SGPO(tree) => tree.get_quads(pattern),
            Self::SGOP(tree) => tree.get_quads(pattern),
            Self::PSOG(tree) => tree.get_quads(pattern),
            Self::PSGO(tree) => tree.get_quads(pattern),
            Self::POSG(tree) => tree.get_quads(pattern),
            Self::POGS(tree) => tree.get_quads(pattern),
            Self::PGSO(tree) => tree.get_quads(pattern),
            Self::PGOS(tree) => tree.get_quads(pattern),
            Self::OSPG(tree) => tree.get_quads(pattern),
            Self::OSGP(tree) => tree.get_quads(pattern),
            Self::OPSG(tree) => tree.get_quads(pattern),
            Self::OPGS(tree) => tree.get_quads(pattern),
            Self::OGSP(tree) => tree.get_quads(pattern),
            Self::OGPS(tree) => tree.get_quads(pattern),
            Self::GSPO(tree) => tree.get_quads(pattern),
            Self::GSOP(tree) => tree.get_quads(pattern),
            Self::GPSO(tree) => tree.get_quads(pattern),
            Self::GPOS(tree) => tree.get_quads(pattern),
            Self::GOSP(tree) => tree.get_quads(pattern),
            Self::GOPS(tree) => tree.get_quads(pattern),
        }
    }

    pub fn insert(&mut self, quad: &[I; 4]) -> Option<bool>{
        match &mut self {
            Self::SPOG(tree) => tree.insert(&quad),
            Self::SPGO(tree) => tree.insert(&quad),
            Self::SOPG(tree) => tree.insert(&quad),
            Self::SOGP(tree) => tree.insert(&quad),
            Self::SGPO(tree) => tree.insert(&quad),
            Self::SGOP(tree) => tree.insert(&quad),
            Self::PSOG(tree) => tree.insert(&quad),
            Self::PSGO(tree) => tree.insert(&quad),
            Self::POSG(tree) => tree.insert(&quad),
            Self::POGS(tree) => tree.insert(&quad),
            Self::PGSO(tree) => tree.insert(&quad),
            Self::PGOS(tree) => tree.insert(&quad),
            Self::OSPG(tree) => tree.insert(&quad),
            Self::OSGP(tree) => tree.insert(&quad),
            Self::OPSG(tree) => tree.insert(&quad),
            Self::OPGS(tree) => tree.insert(&quad),
            Self::OGSP(tree) => tree.insert(&quad),
            Self::OGPS(tree) => tree.insert(&quad),
            Self::GSPO(tree) => tree.insert(&quad),
            Self::GSOP(tree) => tree.insert(&quad),
            Self::GPSO(tree) => tree.insert(&quad),
            Self::GPOS(tree) => tree.insert(&quad),
            Self::GOSP(tree) => tree.insert(&quad),
            Self::GOPS(tree) => tree.insert(&quad),
        }
    }

    pub fn size(&self) -> Option<usize>{
        match &self {
            Self::SPOG(tree) => tree.size(),
            Self::SPGO(tree) => tree.size(),
            Self::SOPG(tree) => tree.size(),
            Self::SOGP(tree) => tree.size(),
            Self::SGPO(tree) => tree.size(),
            Self::SGOP(tree) => tree.size(),
            Self::PSOG(tree) => tree.size(),
            Self::PSGO(tree) => tree.size(),
            Self::POSG(tree) => tree.size(),
            Self::POGS(tree) => tree.size(),
            Self::PGSO(tree) => tree.size(),
            Self::PGOS(tree) => tree.size(),
            Self::OSPG(tree) => tree.size(),
            Self::OSGP(tree) => tree.size(),
            Self::OPSG(tree) => tree.size(),
            Self::OPGS(tree) => tree.size(),
            Self::OGSP(tree) => tree.size(),
            Self::OGPS(tree) => tree.size(),
            Self::GSPO(tree) => tree.size(),
            Self::GSOP(tree) => tree.size(),
            Self::GPSO(tree) => tree.size(),
            Self::GPOS(tree) => tree.size(),
            Self::GOSP(tree) => tree.size(),
            Self::GOPS(tree) => tree.size(),
        }
    }

}
